db:
  dsn: "user:password@tcp(localhost:3306)/dbname?parseTime=true&loc=Local"
  connection:
    maxOpenConns: 100
    maxIdleConns: 50
api:
  siteURL: ""
  addr: ":8080"
  tls: false
  tlsCertFile: ""
  tlsKeyFile: ""
  cors:
    enable: false
    origins:
      - # "http://127.0.0.1:8080"
    headers:
      - "*"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    debug: false
worker:
  num: 100
providers:
  # nexmo:
  #   key: "NEXMO_KEY"
  #   secret: "NEXMO_SECRET"
  #   webhook:
  #     enable: true